
// FILMS

export const ALL_FILMS_REQUEST = 'ALL_FILMS_REQUEST'
export const ALL_FILMS_SUCCESS = 'ALL_FILMS_SUCCESS'
export const ALL_FILMS_FAILURE = 'ALL_FILMS_FAILURE'

// PEOPLE

export const ALL_PEOPLE_REQUEST = 'ALL_PEOPLE_REQUEST'
export const ALL_PEOPLE_SUCCESS = 'ALL_PEOPLE_SUCCESS'
export const ALL_PEOPLE_FAILURE = 'ALL_PEOPLE_FAILURE'