
// FILMS

export const ALL_FILMS_REQUEST = 'ALL_FILMS_REQUEST'
export const ALL_FILMS_SUCCESS = 'ALL_FILMS_SUCCESS'
export const ALL_FILMS_FAILURE = 'ALL_FILMS_FAILURE'
export const SINGLE_FILM_REQUEST = 'SINGLE_FILM_REQUEST'
export const SINGLE_FILM_SUCCESS = 'SINGLE_FILM_SUCCESS'
export const SINGLE_FILM_FAILURE = 'SINGLE_FILM_FAILURE'

// PEOPLE

export const ALL_PEOPLE_REQUEST = 'ALL_PEOPLE_REQUEST'
export const ALL_PEOPLE_SUCCESS = 'ALL_PEOPLE_SUCCESS'
export const ALL_PEOPLE_FAILURE = 'ALL_PEOPLE_FAILURE'